### ISSUE TITLE
Ensure application runs smoothly on PHP 7.2

### ISSUE THREAD

**Issue by ottlinger** [ottlinger/hornherzogen#128]
* Premature End of Script - remove everything that is before <?php
* Try Docker integration to verify it's working in an Ubuntu environment

**Comment by ottlinger** [comment]
Furthermore MessageFormatter seems to be make trouble:

```
[Sun Feb 24 20:48:41.538705 2019] [php7:error] [pid 14965] [client 127.0.0.1:46824] PHP Fatal error:  Uncaught Error: Class 'MessageFormatter' not found in /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php:46\nStack trace:\n#0 /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php(21): hornherzogen\\HornLocalizer->getMessageFormatterForKeyWithLanguageFallback('FORM.TITLE')\n#1 /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php(16): hornherzogen\\HornLocalizer->i18nParams('FORM.TITLE', Array)\n#2 /var/srv/Documents/workspace/hornherzogen/index.php(15): hornherzogen\\HornLocalizer->i18n('FORM.TITLE')\n#3 {main}\n  thrown in /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php on line 46
[Sun Feb 24 20:48:45.907362 2019] [php7:error] [pid 14746] [client 127.0.0.1:46864] PHP Fatal error:  Uncaught Error: Class 'MessageFormatter' not found in /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php:46\nStack trace:\n#0 /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php(21): hornherzogen\\HornLocalizer->getMessageFormatterForKeyWithLanguageFallback('FORM.TITLE')\n#1 /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php(16): hornherzogen\\HornLocalizer->i18nParams('FORM.TITLE', Array)\n#2 /var/srv/Documents/workspace/hornherzogen/index.php(15): hornherzogen\\HornLocalizer->i18n('FORM.TITLE')\n#3 {main}\n  thrown in /var/srv/Documents/workspace/hornherzogen/src/hornherzogen/HornLocalizer.php on line 46
```
